---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptobot-cm
data:
  application.properties: |
    spring.data.cassandra.keyspace-name=sample
    spring.data.cassandra.port=9042
    spring.data.cassandra.contact-points=192.168.68.105
    spring.data.cassandra.local-datacenter=datacenter1
    is_local=false
    logging.level.za.co.s2c=DEBUG
    logging.level.root=DEBUG