apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cc-harvester
  name: cc-harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-harvester
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cc-harvester
    spec:
      containers:
        - image: rbuhrmann/cc-harvester
          name: cc-harvester
          resources: {}
status: {}