apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cc-harvester
  name: cc-harvester
spec:
  ports:
    - name: 9090-8080
      port: 9090
      protocol: TCP
      targetPort: 8080
  selector:
    app: cc-harvester
  type: ClusterIP
status:
  loadBalancer: {}