apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cc-candler
  name: cc-candler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-candler
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cc-candler
    spec:
      containers:
        - image: rbuhrmann/cc-candler
          name: cc-candler
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - configMap:
            items:
              - key: application.properties
                path: application.properties
            name: candler-cm
          name: config
status: {}